Add 2D plotting script PostFit2DShapesFromWorkspace.cpp
cms-analysis/CombineHarvester pull request #327
Opened 2024-06-19 12:13 UTC by mroguljic

Resurrection of [this PR](https://github.com/cms-analysis/CombineHarvester/pull/223). I just checked that it compiles on el9.
@ajgilbert your comment on code duplication still stands, but it has been some time since the linked PR and I'm not sure if these functionalities have been added.

2024-07-01 09:38 UTC, ajgilbert requested changes
Hi,

The code introduces a lot of duplication, which is not ideal. That said, it can be merged pending a number of issues (see the code comments for details).

2024-07-01 09:38 UTC, ajgilbert commented on CombineTools/src/CombineHarvester.cc
> +            var_name_y = temp_vars->first()->GetName();
Do we not need to check the data object actually has two observables first? Won't this crash if we only have one?

2024-07-01 09:38 UTC, ajgilbert commented on CombineTools/src/CombineHarvester.cc
> +          entry->set_observable_y(
As above, surely we only want to call this if there is a 2nd observables?

2024-07-01 09:38 UTC, ajgilbert commented on CombineTools/interface/Process.h
> +  RooRealVar* cached_obsy_;
In Process.cc, need to handle this new data member correctly in all constructors, assignment and swap methods.

2024-07-01 09:38 UTC, ajgilbert commented on CombineTools/src/CombineHarvester_Evaluate.cc
> +        RooArgSet* temp_vars = (RooArgSet*)data_obj->get()->Clone();
Check memory ownership of cloned object

2024-07-03 12:54 UTC, mroguljic commented
Thank you for the review @ajgilbert 
The PR was updated per your comments. I tested it on my usual 2D workflows, do you have some workflows that I could run to ensure it does not break the typical 1D case?

2024-07-03 16:26 UTC, ajgilbert commented
Thanks, I think you could run on any set of 1D cards. For example there are some in the tutorials section: https://github.com/cms-analysis/HiggsAnalysis-CombinedLimit/tree/main/data/tutorials/htt/125

2024-07-10 09:51 UTC, mroguljic reviewed
Implemented

2024-07-10 19:37 UTC, ajgilbert approved these changes

2024-07-22 14:59 UTC, merged

2024-08-14 14:44 UTC, lcorcodilos commented
🎉 Thanks for getting this over the line @mroguljic and @ajgilbert! And glad to see it's still providing value 😄